version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: infra/php/Dockerfile
    volumes:
      - ./src:/data
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: infra/nginx/Dockerfile
      # image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
    networks:
      - app-network

  mysql:
    container_name: mysql
    # 明示的にcontext指定
    build: 
      context: .
      dockerfile: infra/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql
    networks:
      - app-network
    ports:
      - 3306:3306


volumes:
  db-store:

networks:
  app-network:
