version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: infra/php/Dockerfile
    volumes:
      - ./src:/data

  web:
    build:
      context: .
      dockerfile: infra/nginx/Dockerfile
      # image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    # 明示的にcontext修正
    build: 
      context: .
      dockerfile: infra/mysql/Dockerfile
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store:
  